eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://192.168.119.131:8761/eureka/

spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://192.168.0.24/world
    username: admini
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8886
