eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    #是否注册到注册中心
    register-with-eureka: true
    #抓取服务的IP
    fetch-registry: true
    serviceUrl:
      defaultZone: http://192.168.119.131:8761/eureka/

spring:
  application:
    name: useruifeign

server:
  port: 80
